# Site
title: lovexy's blog
subtitle: "lovexy's blog"
author: lovexy
language: zh
timezone:

# URL
url: https://blog.lovexy.fun/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Site settings
SEOTitle: lovexy's blog
email: lovexyfun@gmail.com
description: "lovexy's blog"
keyword: "lovexy,lovexy-fun"

# SNS settings
github_username: lovexy-fun

# Build settings
anchorjs: true

sidebar-avatar: img/avatar.jpg
avatar_style:
  radius: true

# Friends
friends: [
    {
        title: "鲁ICP备2020039203号",
        href: "https://beian.miit.gov.cn/"
    }
]

search:
  path: search.json
  field: post

# 文章样式(是否首行缩进)：
post_style:
  indent: 0

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archive
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: aircloud

# Deployment
deploy:
  type: git
  repo: git@github.com:lovexy-fun/lovexy-fun.github.io.git
  branch: master
